// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.ValueChange("main_frame", "sel_parts", "0");
            akit.ValueChange("main_frame", "sel_parts", "1");
            akit.ValueChange("main_frame", "sel_objects_in_joints", "1");
            akit.Callback("acmdSelectAll", "", "main_frame");
            akit.Callback("acmd_display_partnumbers_set_options", "", "main_frame");
            akit.ValueChange("m3_dialog", "saveas_file", "currentUsersSettings");
            akit.PushButton("attrib_saveas", "m3_dialog");
            akit.ValueChange("m3_dialog", "get_menu", "renumberBeforeDrawingsSingle");
            akit.PushButton("attrib_get", "m3_dialog");
            akit.PushButton("m3_apply", "m3_dialog");
            akit.PushButton("m3_ok", "m3_dialog");
            akit.Callback("acmd_unnumber_selected_parts", "part_and_assembly_and_rebar", "main_frame");
            akit.PushButton("warning_ok", "cleared_selected_numbering");
            akit.ModalDialog(1);
            akit.Callback("acmd_partnumbers_all", "", "main_frame");
            akit.Callback("acmd_display_partnumbers_set_options", "", "main_frame");
            akit.ValueChange("m3_dialog", "get_menu", "currentUsersSettings");
            akit.PushButton("attrib_get", "m3_dialog");
            akit.PushButton("m3_apply", "m3_dialog");
            akit.PushButton("m3_ok", "m3_dialog");
            akit.Callback("acmd_display_partnumbers_set_options", "", "main_frame");
            akit.ValueChange("m3_dialog", "get_menu", "currentUsersSettings");
            akit.PushButton("attrib_get", "m3_dialog");
            akit.PushButton("m3_apply", "m3_dialog");
            akit.PushButton("m3_ok", "m3_dialog");
        }
    }
}
