// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmdDisplayObjectRepresentationDialog", "ViewMenu", "main_frame");
            akit.PushButton("dia_modify", "diaObjectRepresentation");
            akit.PushButton("dia_cancel", "diaObjectRepresentation");
        }
    }
}
