// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmdDisplayOpenModelDialog", "", "main_frame");
            akit.PushButton("exit_save", "close_confirm_dialog");
            akit.PushButton("OpenModelOkButton", "OpenModelDialog");
        }
    }
}
