// Generated by Tekla.Technology.Akit.ScriptBuilder

namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {

            akit.Callback("acmd_draw_selected_hidden_lines", "own", "View_01 window_1");
 
        }
    }
}
